### ISSUE TITLE
Unmerge cells only unmerges the cells visually

### ISSUE THREAD

**Issue by ShadowKyogre** [manns/pyspread#123] opened 2015-11-15 01:30 UTC
Steps to reproduce:

1. Merge some cells after entering some values
2. Click unmerge cells
3. You should get two "blank" cells and one cell that has the first value of the merged cells
4. Click one of the blank cells

Expected result:
The unmerged cell should be able to be edited separately from the cell it used to be merged to.

Actual result:
The unmerged cell still has its value linked to the first cell in the merge group.

**Comment by manns** [comment] 2015-11-15 09:21
The actual result is actually the intended behavior.

This solves the issue that when cells that are hidden by a merge were still active, unintended behavior  was common, i.e. the cells that were hidden did things to the spreadsheet and no one could trace the reason. Therefore, hidden cells become disabled and emptied when they are merged.

Is there a use case, in which the current behavior causes an issue?

**Comment by ShadowKyogre** [comment] 2015-11-15 18:39
Yes, there's a use case where it causes an issue. It came up when I was rearranging one of the sheets to have prettier formatting by having one header row on it. So instead of moving the rest of the contents down (like I probably should've) before turning the first row into one merged row, I just started directly working with the first row and merged four of the cells together. Then I unmerged those cells thinking that maybe that wasn't the best way to format one of the tables.

Which lead to this bug report. Merging the cells and then unmerging them essentially renders the previously merged ones unusable on their own. I'm not sure what's the recommended workaround if there's a row filled with merged cells that were made by accident. From what it looks like, the user'd have to manually copy everything but the accidentally merged cells onto another table before deleting the table that had the accidental merged cells.

**Comment by manns** [comment] 2015-12-29 17:03
I consider this an important issue because the undo function does not work correctly when unmerging cells.  Therefore, the cell content is truly lost, which is a bug.

Since cell content can be easily shifted by the user, I opt against both an automatism to keep code going and invisible and uneditable cell code in merged cells.

**Comment by manns** [comment] 2015-12-29 18:58
I have fixed the undo bug in the master branch.  I close the issue because I see no good solution to your use case that does not imply any "magic".

@ShadowKyogre: If you have a proposal how to improve the situation, which does not rely on execution of hidden code, please do not hesitate to re-open this issue.

**Closed by manns** 2015-12-29 18:58 UTC
Labels: Feature request
