### ISSUE TITLE
IOError: [Errno 17] No usable temporary file name found

### ISSUE THREAD

**Issue by Mintaka** [manns/pyspread#122] opened 2015-11-05 10:50 UTC
Hello

Windows XP SP3 Prof.
Python 2.7.10 
pyspread-1.0-win32-setup.exe

D:\Prg\pyspread>pyspread.exe
Traceback (most recent call last):
  File "pyspread", line 243, in <module>
  File "pyspread", line 229, in pyspread
  File "pyspread", line 172, in __init__
  File "wx\_core.pyo", line 7981, in __init__
  File "wx\_core.pyo", line 7555, in _BootstrapApp
  File "pyspread", line 191, in OnInit
  File "src\gui\_main_window.pyo", line 39, in <module>
  File "D:\Prg\pyspread\library.zip\matplotlib\__init__.py", line 824, in <module>
  File "D:\Prg\pyspread\library.zip\matplotlib\__init__.py", line 735, in rc_params
  File "D:\Prg\pyspread\library.zip\matplotlib\__init__.py", line 646, in matplotlib_fname
  File "D:\Prg\pyspread\library.zip\matplotlib\__init__.py", line 278, in wrapper
  File "D:\Prg\pyspread\library.zip\matplotlib\__init__.py", line 521, in _get_configdir
  File "D:\Prg\pyspread\library.zip\matplotlib\__init__.py", line 196, in _is_writable_dir
  File "C:\Python27\lib\tempfile.py", line 475, in NamedTemporaryFile
  File "C:\Python27\lib\tempfile.py", line 257, in _mkstemp_inner
IOError: [Errno 17] No usable temporary file name found

------
Funny is, that on the path: C:\Python27\..
Doesn't exist any Python27.

Maybe some hard coded path somewhere in program.
It is not necessarily to solve this problem, I just want to try pyspread.

Have a good coding time.

**Comment by manns** [comment] 2015-11-05 20:39
Looks like 
http://matplotlib.1069221.n5.nabble.com/Error-17-No-usable-Temporary-file-name-found-td46219.html

**Comment by manns** [comment] 2015-11-05 20:53
I have tried it out in WinXP32bit SP2 and could not reproduce your issue.
Pyspread.exe starts with or without the c:\python2.7 folder.

Have you previously had installed Python 2.7 on your system and removed it again?

Could you post your system and user variables PATH (at least the Python relevant part) and PYTHONPATH?

**Comment by Mintaka** [comment] 2015-11-06 07:03
Hello
Search in registers I found
HKEY_LOCAL_MACHINE\SYSTEM\ControlSet002\Control\Session Manager\Environment
CLOUDSDK_PYTHON=C:\python27_x64\python.exe

Also in user environement variables  cmd -> set
I found variable name CLOUDSDK_PYTHON=C:\python27_x64\python.exe

In the PATH or in the PYTHONPATH or INCLUDE was nothing about c:\python27

After deleting registry key and environent value, still it crash on:
  File "D:\Prg\pyspread\library.zip\matplotlib\__init__.py", line 196, in _is_writable_dir
  File "C:\Python27\lib\tempfile.py", line 475, in NamedTemporaryFile
  File "C:\Python27\lib\tempfile.py", line 257, in _mkstemp_inner
IOError: [Errno 17] No usable temporary file name found

If you look inside pyspread.exe  (mine have 34816 bytes created 2015-09-29 22:49:20) are there explicit strings like: C:\Python27\lib\site-packages\py2exe\boot_common.py

Hava a nice day.


2015-11-05 21:53 GMT+01:00 Martin Manns <notifications@github.com>:

    I have tried it out in WinXP32bit SP2 and could not reproduce your issue.
    Pyspread.exe starts with or without the c:\python2.7 folder.

    Have you previously had installed Python 2.7 on your system and removed it again?

    Could you post your system and user variables PATH (at least the Python relevant part) and PYTHONPATH?

**Comment by manns** [comment] 2015-11-15 22:53
I see these strings. They have been inserted by py2exe. However, On my and other systems everything works well without such a directory. I will look into it before the next release.

Meanwhile, you may install Python in C:\Python27 as a quick fix. After this, pyspread should run fine.

**Comment by manns** [comment] 2016-02-01 20:15
Since I have tested this several times with the 1.1 win32 release and still cannot reproduce it, I close this issue now.

**Closed by manns** 2016-02-01 20:15 UTC
Labels: Cannot reproduce
